### ISSUE TITLE
 Em Aplicar Bolsa, é preciso ter um cadastro do aluno com as informações gerais do aluno

### ISSUE THREAD

**Issue by goombaActivist** [goombaActivist/APS-2023.2-SIGAA#19]
(todo o histórico das disciplinas cursadas, as respectivas bolsas já obtidas e correntes, etc) para permitir, por exemplo, que o método CompatibilidadeBolsa consulte este cadastro e verifique a compatibilidade. Este método não pode ser meramente um método reflexivo do controlador, pois o controlador não tem essas informações.

**Comment by HACardoso** [comment]
Adição de um método ao diagrama de sequências da Aplicar Bolsas que consulta uma nova entidade: Cadastro Discente, para validação da bolsa, não sendo mais um método reflexivo do próprio controlador de bolsa. Adição da nova entidade também no diagrama de classes.
